# 20 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.

### 1. Import the numpy package under the name np (★☆☆)

In [8]:
import numpy as np

### 2. Print the numpy version and the configuration (★☆☆)

In [24]:
print(np.version.version)
print("\n")


1.24.3




In [25]:
print(np.show_config())
print("\n")

blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/ro_be/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/ro_be/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/ro_be/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/ro_be/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/ro_be/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/ro_be/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/ro_be/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/ro_be/anaconda3\\Lib

### 3. Create a null vector of size 10 (★☆☆)

In [14]:
vector_10=np.zeros(10)
print(vector_10)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 4. How to find the memory size of any array (★☆☆)

In [18]:
memory_array=np.array([1,2,3,4,5,6])
print((memory_array.itemsize)*(memory_array.size))

24


### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [27]:
print(np.info(np.add))
print("\n")

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [31]:
vector_10_null=np.zeros(10)
print(vector_10_null)
print("\n")
vector_10_null[4]=1
print(vector_10_null)
print("\n")

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]




### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [36]:
vector_10_49=np.arange(10,50)
print(vector_10_49)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 8. Reverse a vector (first element becomes last) (★☆☆)

In [40]:
flip_array=np.array([1,2,3,4,5,6])
print(flip_array)
print("\n")
flipped_array=np.flip(flip_array)
print(flipped_array)
print("\n")


[1 2 3 4 5 6]


[6 5 4 3 2 1]




### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
array=np.arange(9).reshape(3,3)
print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
arr=np.nonzero([[1,2,0,0,4,0]])
print(arr)

(array([0, 0, 0], dtype=int64), array([0, 1, 4], dtype=int64))


### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
arr=np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
random_arr=np.random.rand(3,3)
print(random_arr)

[[0.35844986 0.05874508 0.63778238]
 [0.50502486 0.48272918 0.85425083]
 [0.3518003  0.29087052 0.0829437 ]]


### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [17]:
random_arr=np.random.rand(10,10)
print(random_arr)
print("\n")
print(random_arr.max())
print("\n")
print(random_arr.min())

[[0.8539531  0.85247242 0.07676875 0.872591   0.95080206 0.82613884
  0.32063351 0.64286723 0.33218733 0.89180617]
 [0.24282906 0.25154044 0.12314442 0.24775024 0.77860056 0.22186973
  0.62912031 0.85526634 0.74697393 0.08511624]
 [0.86027124 0.04851423 0.14278438 0.9087309  0.60144398 0.7369875
  0.027819   0.43842554 0.60850556 0.93832224]
 [0.11964745 0.77862154 0.26363848 0.87735539 0.32928889 0.26577198
  0.41831104 0.10219754 0.09154913 0.68764867]
 [0.09927829 0.06861856 0.93777887 0.44501301 0.41152253 0.01244086
  0.19632504 0.89178204 0.70758226 0.14981079]
 [0.02600589 0.42781607 0.28347327 0.47379592 0.20788053 0.74876934
  0.16094754 0.88990023 0.6810303  0.55307381]
 [0.66468085 0.75222623 0.33734059 0.53362554 0.82806472 0.9331586
  0.39758106 0.02151264 0.00965454 0.98539634]
 [0.98654928 0.77062803 0.36341845 0.44315118 0.31647031 0.25944137
  0.34824208 0.91827899 0.77252076 0.40090919]
 [0.66114377 0.26547951 0.36637786 0.53755079 0.05918792 0.34754916
  0.42725345 0

### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [18]:
random_arr=np.random.rand(30,30)
print(random_arr)
print("\n")
print(random_arr.mean())
print("\n")

[[0.30965196 0.71912647 0.62648375 0.91439475 0.67959018 0.77141159
  0.28590035 0.27515872 0.03575334 0.92415951 0.64503644 0.90595151
  0.45061614 0.22675197 0.246099   0.9389687  0.35283644 0.24470285
  0.67938331 0.86799376 0.52146235 0.30744773 0.41505266 0.80185194
  0.03671952 0.51419452 0.57704269 0.06983171 0.9942575  0.41990584]
 [0.44462704 0.40309237 0.22213333 0.38842598 0.33163157 0.8284786
  0.40459277 0.02459591 0.42372949 0.60641475 0.1050847  0.24160928
  0.18239919 0.57108164 0.8093366  0.26060953 0.94509254 0.70374423
  0.24466881 0.59776953 0.44153681 0.37408811 0.77817003 0.00273311
  0.72170801 0.48926789 0.06217806 0.5599333  0.7073889  0.491253  ]
 [0.89354166 0.36198431 0.84321501 0.01398842 0.21801344 0.32470134
  0.55886127 0.76481486 0.10188887 0.94853276 0.16640816 0.59926913
  0.41560255 0.90812813 0.02140141 0.05465374 0.98469977 0.06169107
  0.6029532  0.65990317 0.0960929  0.70352015 0.82773479 0.91009954
  0.10118846 0.23954621 0.53598571 0.20078767 0

### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [25]:
array_center=np.zeros([3,3])
array_center[1,1]=1
print(array_center)


[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]


### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [32]:
array_border=np.arange(1,10).reshape(3,3)
print(array_border)
array_border = np.pad(array_border, pad_width=1, mode='constant', constant_values=0)
print("\n")
print(array_border)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


### 17. What is the result of the following expression? (★☆☆)

In [33]:
# 0 * np.nan
# np.nan == np.nan
# np.inf > np.nan
# np.nan - np.nan
# np.nan in set([np.nan])
# 0.3 == 3 * 0.1

In [35]:
print(0 * np.nan)
print(np.nan == np.nan) 
print(np.inf > np.nan) 
print(np.nan - np.nan) 
print(np.nan in set([np.nan])) 
print( 0.3 == 3 * 0.1)

nan
False
False
nan
True
False


### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [42]:
diag = np.diag(1+np.arange(4),k=-1)
print(diag)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [58]:
checkboard = np.zeros((8,8),dtype=int)
checkboard[1::2, ::2] = 1
checkboard[::2, 1::2] = 1

print(checkboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [59]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)
