In [18]:
import numpy as np

In [3]:
matriz_1=np.array([1,2,3,4,5,6,7,8,9])

In [5]:
print(matriz_1)

[1 2 3 4 5 6 7 8 9]


In [7]:
matriz_2=np.array([[12,34,56,78,90],[10,29,38,47,56],[13,25,46,57,80]])

In [8]:
print(matriz_2)

[[12 34 56 78 90]
 [10 29 38 47 56]
 [13 25 46 57 80]]


In [12]:
lista_3=[1,2,3,4,5]

In [13]:
matriz_3= np.array(lista_3)

In [14]:
print(matriz_3)

[1 2 3 4 5]


In [15]:
matriz_4=np.arange(24).reshape(6,4)

In [16]:
print(matriz_4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [17]:
print(matriz_4.shape)

(6, 4)


In [19]:
print(matriz_4.ndim)

2


In [20]:
print(matriz_4.size)

24


In [22]:
matriz_5=np.zeros((3,5))

In [23]:
print(matriz_5)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [24]:
matriz_6=np.arange(10)

In [25]:
print(matriz_6)

[0 1 2 3 4 5 6 7 8 9]


In [27]:
matriz_7=np.linspace(99,88,25)

In [28]:
print(matriz_7)

[99.         98.54166667 98.08333333 97.625      97.16666667 96.70833333
 96.25       95.79166667 95.33333333 94.875      94.41666667 93.95833333
 93.5        93.04166667 92.58333333 92.125      91.66666667 91.20833333
 90.75       90.29166667 89.83333333 89.375      88.91666667 88.45833333
 88.        ]


In [30]:
matriz_8=np.arange(24).reshape(2,3,4)

In [31]:
print(matriz_8)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [32]:
matriz_9 = np.arange(27).reshape(3,9)

In [34]:
print(matriz_9)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]]


In [36]:
matriz_10= np.array([99,10,88,20,77,30,66,40,55])

In [38]:
print(np.sort(matriz_10))

[10 20 30 40 55 66 77 88 99]


In [39]:
matriz_11= np.array([2,3])

In [41]:
print(np.power(matriz_11,3))

[ 8 27]


In [42]:
matriz_12= np.array([99,10,88,20,77,30,66,40,55])

In [44]:
print(np.array(matriz_12>50))

[ True False  True False  True False  True False  True]


In [47]:
print(np.array(matriz_12.max()))

99


In [48]:
print(np.array(matriz_12.min()))

10


In [51]:
matriz_13= np.array([90,11,80,22,70,33,60,44,50])

In [52]:
print(np.concatenate((matriz_12,matriz_13)))

[99 10 88 20 77 30 66 40 55 90 11 80 22 70 33 60 44 50]


In [53]:
m1=np.array([[1,2],[3,4]])

In [54]:
m2=np.array([[5,6],[7,8]])

In [55]:
print(m1+m2)

[[ 6  8]
 [10 12]]


In [57]:
print(m1.dot(m2))

[[19 22]
 [43 50]]


In [77]:
m=np.random.randint(10)
print(m)

9


In [78]:
m=np.random.randint(10,size=(5))
print(m)

[2 8 0 2 1]


In [79]:
m=np.random.randint(10,size=(3,3))
print(m)

[[9 3 3]
 [3 8 5]
 [9 8 7]]


In [80]:
m=np.random.rand(5)
print(m)

[0.35663714 0.5205571  0.87219153 0.38702931 0.21464768]


In [82]:
m=np.random.rand(2,2)
print(m)

[[0.69169004 0.92888962]
 [0.24926061 0.99774222]]


In [96]:
m=np.random.choice([3,5,9,5,1])
print(m)

5


In [95]:
m=np.random.choice([3,5,9,5,1], size=(2,3))
print(m)

[[1 9 1]
 [5 5 5]]


In [130]:
m=np.random.choice([2,4,6],p=[0.5,0.5,0.0],size=[1])
print(m)

[2]


In [142]:
m=np.random.choice([2,4,8,10],p=[0.3,0.5,0.1,0.1],size=[50])
print(m)

[ 2  2 10  4 10  4  4 10  4  2  4  2  2  4  8  2  2  2  8  4  2  4  4  2
  4 10  4  2  4  2  4  2  4 10  4  4  2  4  2  4  8  4  4 10 10  4  4  2
  4 10]


In [144]:
m=np.array([[0,1,2],[4,2,3]])
print(m)
print("\n")
print(np.sum(m,axis=0))

[[0 1 2]
 [4 2 3]]


[4 3 5]


In [145]:
m=np.array([[0,1,2],[4,2,3]])
print(m)
print("\n")
print(np.sum(m,axis=1))

[[0 1 2]
 [4 2 3]]


[3 9]


In [149]:
m=np.array([[1,1],[1,1]])
n=np.array([[2,2],[2,2]])
print(m)
print("\n")
print(n)
print("\n")
print(np.concatenate([m,n],axis=0))

[[1 1]
 [1 1]]


[[2 2]
 [2 2]]


[[1 1]
 [1 1]
 [2 2]
 [2 2]]


In [150]:
m=np.array([[1,1],[1,1]])
n=np.array([[2,2],[2,2]])
print(m)
print("\n")
print(n)
print("\n")
print(np.concatenate([m,n],axis=1))

[[1 1]
 [1 1]]


[[2 2]
 [2 2]]


[[1 1 2 2]
 [1 1 2 2]]


In [153]:
m=np.array([1,1])
n=np.array([2,2])
print(m)
print("\n")
print(n)
print("\n")
print(np.concatenate([m,n],axis=0))

[1 1]


[2 2]


[1 1 2 2]


In [159]:
n=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(n)
print("\n")
print(np.amin(n))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


1


In [158]:
n=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(n)
print("\n")
print(np.amax(n))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


9


In [160]:
n=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(n)
print("\n")
print(np.amin(n,1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[1 4 7]


In [161]:
n=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(n)
print("\n")
print(np.ptp(n))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


8


In [162]:
n=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(n)
print("\n")
print(np.ptp(n,axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[2 2 2]


In [163]:
n=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(n)
print("\n")
print(np.percentile(n,50))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


5.0


In [164]:
n=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(n)
print("\n")
print(np.percentile(n,50,axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[2. 5. 8.]


In [165]:
n=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(n)
print("\n")
print(np.median(n))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


5.0


In [166]:
n=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(n)
print("\n")
print(np.median(n,axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[4. 5. 6.]


In [167]:
n=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(n)
print("\n")
print(np.mean(n))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


5.0


In [168]:
n=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(n)
print("\n")
print(np.mean(n,axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[4. 5. 6.]


In [171]:
n=np.array([1,2,3,4,5,6])
print(n)
print("\n")
print(np.average(n))

[1 2 3 4 5 6]


3.5


In [172]:
n=np.array([1,2,3,4,5,6])
print(n)
print("\n")
print(np.std(n))

[1 2 3 4 5 6]


1.707825127659933


In [177]:
m=np.array([[1,-1,2],[3,2,0]])
print(m)
print("\n")
m1=np.array([[1],[2],[3]])
print(m1)
print("\n")
print(np.transpose(m1))

[[ 1 -1  2]
 [ 3  2  0]]


[[1]
 [2]
 [3]]


[[1 2 3]]


In [185]:
ma=np.array([[2,1,-2],[3,0,1],[1,1,-1]])
print(ma)
print("\n")
mb=np.array([[-3],[5],[-2]])
print(mb)
print("\n")
print(np.transpose(mb))
print("\n")
x=np.linalg.solve(ma,mb)
print(x)

[[ 2  1 -2]
 [ 3  0  1]
 [ 1  1 -1]]


[[-3]
 [ 5]
 [-2]]


[[-3  5 -2]]


[[ 1.]
 [-1.]
 [ 2.]]


In [188]:
ma=np.array([[2,1,-2],[3,0,1],[1,1,-1]])
print(ma)
print("\n")
mb=np.array([[-3],[5],[-2]])
print(mb)
print("\n")
print(np.transpose(mb))
print("\n")
x=np.linalg.solve(ma,mb)
print(x)
print("\n")
print(np.allclose(np.dot(ma,x),mb))

[[ 2  1 -2]
 [ 3  0  1]
 [ 1  1 -1]]


[[-3]
 [ 5]
 [-2]]


[[-3  5 -2]]


[[ 1.]
 [-1.]
 [ 2.]]


True


In [198]:
m1=np.array([[2,7,3],[2,8,2],[1,3,1]])
print(m1)
print("\n")
m2=np.array([1,1,0])
m2.shape=(3,1)
print(m2)
print("\n")
print(np.linalg.solve(m1,m2))

[[2 7 3]
 [2 8 2]
 [1 3 1]]


[[1]
 [1]
 [0]]


[[-2. ]
 [ 0.5]
 [ 0.5]]
